### ISSUE TITLE
script breaks if a property namespace cannot be found

### ISSUE THREAD

**Issue by JoshQuaintance** [kastle-lab/documentation-generator#9]
This is specifically for the `get_namespace` method.  [method](https://github.com/kastle-lab/documentation-generator/blob/master/documentation-generator/documentation-generator.py#L8-L13)  
 
Currently if it cannot find one, then it will return a `None`.
The method `get_predicate` uses `get_namespace` and tries to do `namespace + prefix`, if namespace is `None`, it will throw an exception.  

Right now a fix could be replacing `None` with `rdflib.term.URIRef("")` (An empty URI Reference) and this will let the script run.

From:
```python
def get_namespace(prefix, graph):
	'''Iterate through the namespaces and return the match'''
	for p, ns in graph.namespaces():
		if p == prefix:
			return ns
	return None #<<<
```
To:
```python
def get_namespace(prefix, graph):
	'''Iterate through the namespaces and return the match'''
	for p, ns in graph.namespaces():
		if p == prefix:
			return ns
	return rdflib.term.URIRef("") #<<<
```

**Comment by cogan-shimizu** [comment]
I think the solution is not the empty namespace, but instead to use a placeholder.

In the `get_namespace` function, let's add a clause after the breaking for loop to add in a prefix called "missing" with "https://missing.com/" as the URIRef and then return that.
